@startuml
title Classes - AlgoStars

class Jugador {
}

interface Edificio {
    -vida
    -ubicacion: Casillero
    {abstract}+ pasarTurno()
    + recibirDaño(daño)
    + setEstadoEnergetico(estado)?
    + construir(Inventario, Casillero)
    + destruir()
}

class EdificioConcreto{
+construir()
}

class EdificioEnConstruccion {
    - vaASer: Edificio
    - turnosRestantes
    + pasarTurno()
}

class EdificioProto {
    - escudo
    - estadoEnergetico
    + recibirDaño(daño)
    + pasarTurno()
    '+ estaActivo()'
    + setEstadoEnergetico(estado)
}

class EdificioZerg {
    + pasarTurno()
}

class Casillero {
    + tieneEnergia()
    + pasarTurno()
    - estaOcupado
}

class Mineral {
 - cantidad
 + agregar(int: cantidad)
 + total()
 + sumar(Mineral: mineral)
}

class Gas {
 - cantidad
 + agregar(int: cantidad)
 + total()
 + sumar(Gas: gas)
}

class Moho {
    + pasarTurno()
    + tieneEnergia()
}

class Inventario {
}

interface TipoCasillero{}



Casillero --> TipoCasillero

NodoGas <- TipoCasillero
TipoCasillero --> NodoMineral
TipoCasillero --> CasilleroVacio
TipoCasillero -> Moho

Inventario o-- Gas
Inventario o-- Mineral

Mapa "1" *- "*" Casillero
Casillero -> Mapa

Edificio "*"--o "1" Inventario
Edificio "1"-->"1" Casillero


Edificio <|... EdificioConcreto
Edificio <|... EdificioEnConstruccion
EdificioConcreto <|... EdificioZerg
EdificioConcreto <|... EdificioProto


Jugador "1" o--> "1" Inventario
@enduml