@startuml
title Modelado de los Edificios Protoss
note "Inventario y Casillero se explican en sus respectivos UMLs" as N1


class EdificioProtoss{
 + <u>EdificioProtoss(Casillero casillero, Inventario inventario, int vidaInicial, int escudoInicial)
 + void:pasarTurno()
}


class Acceso {
 + Acceso(unCasillero, unInventario)
 + void: pasarTurno()
 + int: turnosParaConstruir()
 + {static} EdificioEnConstruccion:construir(casillero, inventario)
}

class Asimilador {
 + Asimilador(unCasillero, unInventario)
 + void: pasarTurno()
 + int: turnosParaConstruir()
 + {static} EdificioEnConstruccion:construir(casillero, inventario)
 + int: extraerGas()
}

class NexoMineral {
 + NexoMineral(unCasillero, unInventario)
 + void: pasarTurno()
 + int: turnosParaConstruir()
 + {static} EdificioEnConstruccion:construir(casillero, inventario)
 + int: extraerMineral()
}

class Pilon {
 + Pilon(unCasillero, unInventario)
 + void: pasarTurno()
 + int: turnosParaConstruir()
 + {static} EdificioEnConstruccion:construir(casillero, inventario)
}

class PuertoEstelar {
 + PuertoEstelar(unCasillero, unInventario)
 + void: pasarTurno()
 + int: turnosParaConstruir()
 + {static} EdificioEnConstruccion:construir(casillero, inventario)
}

EdificioProtoss <|-- PuertoEstelar
EdificioProtoss <|-- Pilon
EdificioProtoss <|-- NexoMineral
EdificioProtoss <|-- Asimilador
EdificioProtoss <|-- Acceso


@enduml