@startuml
'https://plantuml.com/class-diagram
title Modelado de  Juego
note "Las clases se explican\n en sus respectivos UMLs" as N1

class Juego {
- <u>int: cantidadJugadores
- int: cantidadJugadores
- int: turnos

+<u> Juego()
+ void: registrarJugador(String nombre, String color, String raza, String jugador)
+ void: crearTerreno()
+ void: crearBases(int cantBasesPares)
+ void: pasarTurno()
+ String: verificarGanador()
+ int: cantidadDeJugadores()
+ int: cantidadJugadoresMaxima()
}


Juego"1" *-- "2"Jugador
Juego"1" *-- "1"Mapa

@enduml