@startuml
'https://plantuml.com/class-diagram
title Modelado de  Juego
note "Las clases se explican\n en sus respectivos UMLs" as N1

class Juego {
- <u>int: cantidadJugadores
- int: cantidadJugadores
- int: turnos

+<u> Juego()
+ void: registrarJugador(String nombre, String color, String raza, String jugador)
+ void: crearTerreno()
+ void: crearBases(int cantBasesPares)
+ void: pasarTurno()
+ String: verificarGanador()
+ int: cantidadDeJugadores()
+ int: cantidadJugadoresMaxima()
}

interface Unidad{}
note left: Se utiliza la interfaz para representar \n sus implementaciones

Juego"1" *-- "2"Jugador
Juego"1" *-- "1"Mapa
Jugador *-- Inventario
Inventario "1" --> " *" Unidad

Unidad --> Casillero
Unidad "1"--> "1" Inventario

Mapa "1" <-- "1" Casillero
Casillero "*" <-- "1" Mapa
Casillero "1" *-- "1" TipoCasillero
@enduml