@startuml
'https://plantuml.com/class-diagram

title Modelado de  Jugador

class Jugador {
    -String: nombre
    -String: raza
    -String color;

    +<u>Jugador()
    +void: setDatos(String nombre, String color, String raza)
    +boolean: nombreValido(String nombre, Jugador[] jugadores)
    +boolean: colorValido(String color, Jugador[] jugadores)
    +boolean: razaValida(String raza, Jugador[] jugadores)
    +boolean: tieneEdificios()
    + EdificioEnConstruccion: crearBase(Casillero casillero)

}

Jugador *-- Inventario

@enduml