@startuml
'https://plantuml.com/class-diagram

title Jugador

class Jugador {
    -String: nombre
    -String: raza
    -Inventario: inventario

    +<u>Jugador()
    +void: setDatos(String nombre, String color, String raza)
    +boolean: nombreValido(String nombre, Jugador[] jugadores)
    +boolean: colorValido(String color, Jugador[] jugadores)
    +boolean: razaValida(String raza, Jugador[] jugadores)
    +boolean: tieneEdificios()

}

@enduml